# Generated by Django 5.0.3 on 2024-03-10 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_reps', models.PositiveSmallIntegerField(blank=True)),
                ('new_sets', models.PositiveSmallIntegerField(blank=True)),
                ('duration', models.PositiveSmallIntegerField()),
                ('new_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('default_exercise', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='exercisehub.exercise')),
            ],
        ),
    ]
