# Generated by Django 5.0.3 on 2024-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0002_exercisecustom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekday',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='start_distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='start_reps',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='start_sets',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
