# Generated by Django 5.0.3 on 2024-03-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0003_alter_weekday_options_alter_exercise_start_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseachievement',
            name='achieved_distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseachievement',
            name='achieved_reps',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exerciseachievement',
            name='achieved_sets',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercisecustom',
            name='new_distance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exercisecustom',
            name='new_reps',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercisecustom',
            name='new_sets',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
