# Generated by Django 5.0.3 on 2024-03-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0004_alter_exerciseachievement_achieved_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='muscle',
            new_name='muscles',
        ),
        migrations.RenameField(
            model_name='muscle',
            old_name='name',
            new_name='muscle',
        ),
    ]
