# Generated by Django 5.0.3 on 2024-03-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0007_alter_exercisecustom_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='weekday',
        ),
        migrations.AddField(
            model_name='weekday',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='exercisehub.plan'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlanWeekday',
        ),
    ]
