# Generated by Django 5.0.3 on 2024-03-11 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0008_remove_plan_weekday_weekday_plan_delete_planweekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='exercisehub.plan'),
        ),
    ]
