# Generated by Django 5.0.3 on 2024-03-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0009_alter_weekday_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='user',
        ),
        migrations.AddField(
            model_name='plan',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercisehub.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercisehub.profile'),
            preserve_default=False,
        ),
    ]
