# Generated by Django 5.0.3 on 2024-03-11 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0010_remove_plan_user_remove_tracking_user_plan_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='exercisehub.profile'),
        ),
    ]
