# Generated by Django 5.0.3 on 2024-03-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0011_alter_plan_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='weight_gained',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='weight_lost',
        ),
    ]
