# Generated by Django 5.0.3 on 2024-03-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0012_remove_assessment_weight_gained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='exercisehub.profile'),
            preserve_default=False,
        ),
    ]
