# Generated by Django 5.0.3 on 2024-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0013_assessment_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='weight',
            new_name='start_weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_now',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5),
            preserve_default=False,
        ),
    ]
