# Generated by Django 5.0.3 on 2024-03-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0016_exerciseachievement_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseachievement',
            name='achieved_distance',
        ),
        migrations.RemoveField(
            model_name='exercisecustom',
            name='new_distance',
        ),
    ]
