# Generated by Django 5.0.3 on 2024-03-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0017_remove_exerciseachievement_achieved_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='start_distance',
        ),
    ]
