# Generated by Django 5.0.3 on 2024-03-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exercisehub', '0021_rename_start_reps_exercise_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='profile',
        ),
        migrations.AddField(
            model_name='tracking',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='content_type',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='object_id',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
