# Generated by Django 5.0.3 on 2024-03-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0022_remove_tracking_completion_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercisehub.exercise')),
            ],
        ),
    ]
