# Generated by Django 5.0.3 on 2024-03-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0023_completedexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_plan_completion_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercisehub.profile')),
            ],
        ),
    ]
