# Generated by Django 5.0.3 on 2024-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0024_profiletracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='overall_completion_rate',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProfileTracking',
        ),
    ]
