# Generated by Django 5.0.3 on 2024-03-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0027_remove_weekday_plan_plan_weekday_alter_tracking_plan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('profile', 'weekday')},
        ),
    ]
