# Generated by Django 5.0.3 on 2024-03-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0028_alter_plan_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='exercisehub.weekday'),
        ),
    ]
