# Generated by Django 5.0.3 on 2024-03-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0029_alter_plan_unique_together_alter_plan_weekday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('profile', 'weekday')},
        ),
    ]
