# Generated by Django 5.0.3 on 2024-03-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0030_alter_plan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='weekday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='exercisehub.weekday'),
        ),
    ]
