# Generated by Django 5.0.3 on 2024-03-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0036_completedexercise_time_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedexercise',
            options={'ordering': ['-time_completed']},
        ),
        migrations.AlterField(
            model_name='exerciseachievement',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_achievements', to='exercisehub.exercise'),
        ),
    ]
