# Generated by Django 5.0.3 on 2024-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisehub', '0037_alter_completedexercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_description',
            field=models.CharField(default=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
